import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [show, setShow] = useState<string | null>(null);
  const [name, setName] = useState<string>("")
  const { mutate, error } = trpc.people.assignPerson.useMutation({
    onSuccess: (people) => {
      setShow(`Tu tienes ${people.chosenPerson}`);
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-l from-green-600 via-red-500 to-red-700">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Secret <span className="text-[hsl(280,100%,70%)]">Sanda</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {error && <p>{error.message}</p>}
            {show ? (
              <div className="text-3xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                {show}
              </div>
            ) : (
              <>
                <input
                  className="rounded-md p-2"
                  onChange={(event) => setName(event.currentTarget.value)}
                  type="text"
                  placeholder="Introduzca su nombre..."
                />
                <button
                  disabled={name == ""}
                  onClick={() => mutate({ name: name })}
                  className="rounded-md bg-green-300 p-2"
                >
                  Consigue tu persona
                  </button>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
